### ISSUE TITLE
Can't connect to local MySQL server on BaseSpace

### ISSUE THREAD

**Issue by GingerTai** [beukueb/myflq#5]
I has one problem when I was used MyFLq on BaseSpace which is Illumina analysis platform.
Analysis was failed and the error message show: "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)...etc"
I asked Illumina techsupport before, but they cannot support and trobleshooting this error.

I was used Google Chrome version 57.0.2987.133 (64-bit).

**Comment by beukueb** [comment]
We are also no longer actively supporting the BaseSpace version. You can either run your analysis on http://forensic.ugent.be/ or with docker run it locally on your system. This way you also do not lose iCredits.
